name: CI/CD pipline

on:
  push:
    branches: [ "master" ]

jobs:
  test-app-book:
    name: Run app_book tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare unit tests
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip install -r ./app_book/requirements.txt

      - name: Run unit tests
        run: |
          python -m pytest ./tests/unit
        working-directory: ./app_book

      - name: Run integration tests
        run: |
          python -m pytest ./tests/integration
        working-directory: ./app_book

  test-app-document:
    name: Run app_document tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare unit tests
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip install -r ./app_document/requirements.txt

      - name: Run unit tests
        run: |
          python -m pytest ./tests/unit
        working-directory: ./app_document

      - name: Run integration tests
        run: |
          python -m pytest ./tests/integration
        working-directory: ./app_document

  build-and-push-to-dh:
    name: Build and push to DockerHub
    needs: [ test-app-book ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build docker app_book image
        run: |
          docker build ./app_book -f ./app_book/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/app_book:latest

      - name: Login to DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build and push app_book service image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/app_book:latest

  build-and-push-to-yc:
    name: Build and push to YandexCloud Registry
    needs: [ test-app-document ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build docker image
        run: |
          docker build ./app_document -f ./app_document/Dockerfile --tag cr.yandex/${{ secrets.YC_REGISTRY_ID }}/alimzhanov/app_document:latest

      - name: Login to YC Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: cr.yandex
          username: json_key
          password: ${{ secrets.YC_KEYS }}

      - name: Push tag YC Registry
        run: |
          docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/alimzhanov/app_document:latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [ build-and-push-to-yc ]
    steps:
      - name: Deploy serverless container
        uses: yc-actions/yc-sls-container-deploy@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_KEYS }}
          container-name: ${{ secrets.YC_CONTAINER_NAME }}
          folder-id: ${{ secrets.YC_FOLDER_ID }}
          revision-image-url: cr.yandex/${{ secrets.YC_REGISTRY_ID }}/alimzhanov/app_document:latest
          revision-service-account-id: ${{ secrets.YC_SA_ID }}
          revision-env: |
            POSTGRES_URL_BOOK=postgresql://secUREusER:StrongEnoughPassword)@51.250.26.59:5432/alimzhanov_microservice_db_book
            POSTGRES_URL_DOCUMENT=postgresql://secUREusER:StrongEnoughPassword)@51.250.26.59:5432/alimzhanov_microservice_db_document
            AMQP_URL=amqp://guest:guest123@51.250.26.59:5672/
